backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog en Español" # Used in the UI
  #   folder: "content/posts"
  #   filter: {field: "language", value: "es"}
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}.{{language}}."
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog-es"}
  #     - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Tags", name: "tags", widget: "list"}
  #     - {label: "Fecha de publicación", name: "date", widget: "datetime"}
  #     - {label: "Image", name: "image", widget: "image", required: false}
  #     - {label: "Author", name: "author", widget: "string"}
  #     - {label: "Texto", name: "body", widget: "markdown"}
  #
  # - label: "Privacidad"
  #   name: "privacypolicy"
  #   slug: "privacypolicy.{{language}}."
  #   folder: "content/"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #     - {label: "Type", name: "type", widget: "hidden", default: "page"}
  #     - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Fecha de publicación", name: "date", widget: "datetime"}
  #     - {label: "Author", name: "author", widget: "string", default: "Édukanata"}
  #     - {label: "Texto", name: "body", widget: "markdown"}

  - label: "Nosotros"
    name: "about"
    slug: "about"
    folder: "content/"
    fields:
      - {label: "Title", name: "title", widget: "hidden", default: "Nosotros"}
      - {label: "Logo", name: "avatar", widget: "hidden", default: "logo.svg"}
      - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Fundación Búsqueda y Rescate"}
      - {label: "Texto", name: "body", widget: "markdown"}

  - name: "allies" # Used in routes, e.g., /admin/collections/allies
    label: "Aliados" # Used in the UI
    folder: "content/allies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "language", value: "es"}
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "title", widget: "string"}
      # - {label: "Empty", name: "notext", widget: "hidden", default: "true"}
      - {label: "Foto", name: "image", widget: "image"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      # - {label: "Cargo", name: "designation", widget: "string"}
      # - {label: "País", name: "country", widget: "string"}
      - {label: "Orden", name: "weight", widget: "number", default: 2, valueType: "int", min: 1, max: 101}
      # - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
      # - {label: "Texto", name: "body", widget: "markdown"}

  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Galeria" # Used in the UI
    folder: "content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "language", value: "es"}
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Orden", name: "weight", widget: "number", default: 2, valueType: "int", min: 1, max: 101}
      # - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
      # - {label: "Texto", name: "body", widget: "markdown"}

  - name: "programs" # Used in routes, e.g., /admin/collections/programs
    label: "Programas" # Used in the UI
    folder: "content/programs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "language", value: "es"}
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Foto", name: "image", widget: "image", hint: "Dimensiones 1280x847"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      # - {label: "Cargo", name: "designation", widget: "string"}
      # - {label: "País", name: "country", widget: "string"}
      - {label: "Orden", name: "weight", widget: "number", default: 2, valueType: "int", min: 1, max: 101}
      - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
      - {label: "Texto", name: "body", widget: "markdown"}

  - name: "transparency" # Used in routes, e.g., /admin/collections/programs
    label: "Documentos de transparencia" # Used in the UI
    folder: "content/transparency" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "language", value: "es"}
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Orden", name: "weight", widget: "number", default: 2, valueType: "int", min: 1, max: 101}
      # - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
      - {label: "Documentos", name: "documents", widget: "file", "media_library": {"config":{ "multiple": true}}}
      - {label: "Descripción", name: "body", widget: "markdown"}

  # - name: "newheadquarters" # Used in routes, e.g., /admin/collections/newheadquarters
  #   label: "Nueva Sede" # Used in the UI
  #   folder: "content/newheadquarters" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   filter: {field: "language", value: "es"}
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Nombre", name: "title", widget: "string"}
  #     # - {label: "Foto", name: "image", widget: "image"}
  #     - {label: "Fecha de publicación", name: "date", widget: "datetime"}
  #     # - {label: "Cargo", name: "designation", widget: "string"}
  #     # - {label: "País", name: "country", widget: "string"}
  #     - {label: "Orden", name: "weight", widget: "number", default: 2, valueType: "int", min: 1, max: 101}
  #     - {label: "Idioma", name: "language", widget: "select", default: "es", options: ["es"]}
  #     - {label: "Texto", name: "body", widget: "markdown"}
